[package]
name = "mouse_rate_checker_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1", features = ["wgpu"] }
egui = "0.29.1"
winit = "0.30.5"
crossbeam = "0.8.4"
rfd = "0.15.1"
windows = { version = "0.58.0", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemInformation",
    "Win32_System_Threading"
] }